# Your .github/workflows/coverity.yml file.
name: Coverity Scan

# We only want to test official release code, not every pull request.
on:
  push:
    branches: [main]

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: vapier/coverity-scan-action@v1
      with:
        project: 'New Project test Madhuri'
        email: js185672@ncr.com
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        command: make
